name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Build
        run: cargo build --verbose --bin cli_app
      - name: Test
        run: cargo test --bin cli_app
      - name: Package
        run: cargo build --release --bin cli_app
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: cli_app-macos
          path: target/release/cli_app

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y libdbus-1-dev libhidapi-dev libusb-1.0-0-dev libudev-dev
      - name: Build
        run: cargo build --verbose --bin cli_app
      - name: Test
        run: cargo test --bin cli_app
      - name: Package
        run: cargo build --release --bin cli_app
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: cli_app-linux
          path: target/release/cli_app

  create-release:
    needs: [build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: cli_app-macos
          path: .
          
      - name: Download Linux artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: cli_app-linux
          path: .
    
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
          
      - name: Upload macOS Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cli_app-macos.zip
          asset_name: cli_app-macos
          asset_content_type: application/octet-stream
          
      - name: Upload Linux Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cli_app-linux.zip
          asset_name: cli_app-linux
          asset_content_type: application/octet-stream
